<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\dads-removebg-preview.png" />
    <None Remove="Assets\Icons\alerts-100.png" />
    <None Remove="Assets\Icons\arrow-bottom_left_corner-100.png" />
    <None Remove="Assets\Icons\arrow-top_right_corner-100.png" />
    <None Remove="Assets\Icons\budget-100.png" />
    <None Remove="Assets\Icons\cash-100.png" />
    <None Remove="Assets\Icons\dashboard-100.png" />
    <None Remove="Assets\Icons\logout-100.png" />
    <None Remove="Assets\Icons\plus-100.png" />
    <None Remove="Assets\Icons\settings-100.png" />
    <None Remove="Assets\Icons\transaction-100.png" />
    <None Remove="Assets\loginbutton-removebg-preview.png" />
    <None Remove="Assets\loginbutton.png" />
    <None Remove="Assets\logowword-removebg-preview.png" />
    <None Remove="Assets\logowword.png" />
    <None Remove="Assets\logowwordclear.png" />
    <None Remove="ChatGPT_Image_May_5__2026__09_36_31_PM-removebg-preview.png" />
    <None Remove="dads-removebg-preview.png" />
    <None Remove="loginbutton-removebg-preview.png" />
    <None Remove="loginbutton.png" />
    <None Remove="logowword-removebg-preview.png" />
    <None Remove="logowword.png" />
    <None Remove="logowwordclear.png" />
    <None Remove="sssss.png" />
    <None Remove="View\ChatGPT Image May 16, 2026, 07_26_56 PM.png" />
    <None Remove="View\ChatGPT_Image_May_5__2026__09_36_31_PM-removebg-preview.png" />
    <None Remove="View\logowwordclear.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\dads-removebg-preview.png" />
    <Resource Include="Assets\Icons\alerts-100.png" />
    <Resource Include="Assets\Icons\arrow-bottom_left_corner-100.png" />
    <Resource Include="Assets\Icons\arrow-top_right_corner-100.png" />
    <Resource Include="Assets\Icons\budget-100.png" />
    <Resource Include="Assets\Icons\cash-100.png" />
    <Resource Include="Assets\Icons\dashboard-100.png" />
    <Resource Include="Assets\Icons\logout-100.png" />
    <Resource Include="Assets\Icons\plus-100.png" />
    <Resource Include="Assets\Icons\settings-100.png" />
    <Resource Include="Assets\Icons\transaction-100.png" />
    <Resource Include="Assets\loginbutton-removebg-preview.png" />
    <Resource Include="Assets\loginbutton.png" />
    <Resource Include="Assets\logowword-removebg-preview.png" />
    <Resource Include="Assets\logowword.png" />
    <Resource Include="Assets\logowwordclear.png" />
    <Resource Include="Assets\ChatGPT_Image_May_5__2026__09_36_31_PM-removebg-preview.png" />
    <Resource Include="Assets\sssss.png" />
    <Resource Include="Assets\ChatGPT Image May 16, 2026, 07_26_56 PM.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Fonts\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.7.0" />
    <PackageReference Include="NuGet.Frameworks" Version="7.6.0" />
  </ItemGroup>

</Project>
